// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessDemo.Commons.Database;

namespace ProcessDemo.Commons.Migrations
{
    [DbContext(typeof(AppleTreeDbContext))]
    [Migration("20200529124931_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProcessDemo.Commons.AppleTree", b =>
                {
                    b.Property<int>("AppleTreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AppleYield")
                        .HasColumnType("float");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<int>("FertilizingAgent")
                        .HasColumnType("int");

                    b.Property<double>("WaterConsumption")
                        .HasColumnType("float");

                    b.HasKey("AppleTreeId");

                    b.HasIndex("FarmId");

                    b.ToTable("AppleTrees");
                });

            modelBuilder.Entity("ProcessDemo.Commons.Models.Farm", b =>
                {
                    b.Property<int>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FarmId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("ProcessDemo.Commons.AppleTree", b =>
                {
                    b.HasOne("ProcessDemo.Commons.Models.Farm", "Farm")
                        .WithMany("AppleTrees")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
