// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessDemo.Commons.Database;

namespace ProcessDemo.Commons.Migrations
{
    [DbContext(typeof(AppleTreeDbContext))]
    [Migration("20200502095109_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProcessDemo.Commons.AppleTree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AppleYield")
                        .HasColumnType("float");

                    b.Property<int>("FertilizingAgent")
                        .HasColumnType("int");

                    b.Property<int>("TreeNumber")
                        .HasColumnType("int");

                    b.Property<double>("WaterConsumption")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("AppleTrees");
                });
#pragma warning restore 612, 618
        }
    }
}
